// Daftar pertanyaan untuk kuis
const PERTANYAAN = [
  {q: 'Apa kepanjangan dari KPU?', a: ['Komisi Pengawas Umum','Komisi Pemilihan Umum','Komite Pemilihan Umum','Komite Pengawas Umum'], correct:1},
  {q: 'Siapa yang berhak memilih dalam Pemilu?', a: ['Semua warga negara','Warga negara yang berusia minimal 17 tahun atau sudah menikah','Hanya pegawai negeri','Warga negara berusia di atas 21 tahun'], correct:1},
  {q: 'Pemilu Presiden dan Wakil Presiden dilaksanakan setiap…', a: ['3 tahun','4 tahun','5 tahun','10 tahun'], correct:2},
  {q: 'Yang tidak termasuk peserta Pemilu adalah…', a: ['Partai politik','Calon perseorangan (untuk Pilkada)','Calon anggota DPR','Mahkamah Konstitusi'], correct:3},
  {q: 'Apa singkatan dari DPT dalam Pemilu?', a: ['Daftar Pemilih Tetap','Daftar Pemilihan Terbuka','Daftar Partai Terdaftar','Data Pemilih Terkini'], correct:0},
  {q: 'Kegiatan kampanye Pemilu bertujuan untuk…', a: ['Menyerang lawan politik','Menarik perhatian media','Memperkenalkan visi, misi, dan program peserta Pemilu','Mengubah undang-undang Pemilu'], correct:2},
  {q: 'Hasil Pemilu Presiden dan Wakil Presiden ditetapkan oleh…', a: ['DPR','MPR','KPU','Mahkamah Konstitusi'], correct:2},
  {q: 'Jika terjadi sengketa hasil Pemilu, siapa yang berwenang memutuskan?', a: ['KPU','DPR','Mahkamah Konstitusi','Bawaslu'], correct:2},
  {q: 'KPU adalah lembaga...', a: ['Di bawah Presiden','Di bawah DPR','Di bawah Mahkamah Agung','Independen'], correct:3},
  {q: 'Siapa yang bertanggung jawab menyelenggarakan Pemilu di Indonesia?', a: ['DPR','Presiden','KPU','Mahkamah Agung'], correct:2},
  {q: 'Berapa kali Pemilu dilaksanakan di Indonesia setiap lima tahun?', a: ['1 kali','2 kali','3 kali','4 kali'], correct:0},
  {q: 'Tujuan utama dari pelaksanaan Pemilu yang jujur dan adil adalah...', a: ['Menguntungkan partai besar','Menjamin kedaulatan rakyat','Memperpanjang masa jabatan','Meningkatkan jumlah partai'], correct:1},
  {q: 'Pilkada diselenggarakan untuk memilih...', a: ['Presiden dan Wakil Presiden','DPR dan DPD','Gubernur, Bupati, dan Wali Kota','Kepala Desa dan Lurah'], correct:2},
  {q: 'Pilkada adalah singkatan dari...', a: ['Pemilihan Kepala Desa','Pemilihan Kepala Daerah','Pemilihan Kepala Dunia','Pemilihan Kandidat Daerah'], correct:1},
  {q: 'Pemilu legislatif memilih anggota...', a: ['DPR, DPD, dan DPRD','Presiden dan Wakil Presiden','Gubernur dan Bupati','KPU dan Bawaslu'], correct:0},
  {q: 'TPS adalah singkatan dari...', a: ['Tempat Pendaftaran Suara','Tempat Pemilihan Sosial','Tempat Pengumpulan Surat','Tempat Pemungutan Suara'], correct:3},
  {q: 'JURDIL dalam Pemilu berarti...', a: ['Jujur dan Disiplin','Jujur dan Adil','Jujur dan Demokratis','Jujur dan Loyal'], correct:1},
  {q: 'LUBER dalam Pemilu berarti...', a: ['Luhur, Bersih, Rapi','Langsung, Bersama, Rakyat','Luas, Bersih, Rahasia','Langsung, Umum, Bebas, Rahasia'], correct:3},
  {q: 'Asas-asas Pemilu di Indonesia adalah...', a: ['LUBER dan JURDIL','Cepat dan tepat','Aman dan tertib','Demokratis dan bebas KKN'], correct:0},
  {q: 'Apa kepanjangan dari KPPS?', a: ['Komisi Pelaksana Pemungutan Suara','Komite Pengawas Pemilu Sementara','Kelompok Penyelenggara Pemungutan Suara','Kelompok Pemantau Pemilu Sementara'], correct:2},
  {q: 'Apa tujuan utama diadakannya Pemilu?', a: ['Mengganti pemerintah','Memilih wakil rakyat dan pemimpin secara demokratis','Menurunkan pejabat lama','Membentuk partai baru'], correct:1},
  {q: 'Asas-asas Pemilu di Indonesia dikenal dengan singkatan...', a: ['LUBER dan JURDIL','LURUS','LESTARI','LANCAR'], correct:0},
  {q: 'Pemilih wajib terdaftar dalam...', a: ['DPD','DPR','DPT','KPU'], correct:2},
  {q: 'Yang berhak memilih adalah warga negara yang berusia minimal...', a: ['15 tahun','17 tahun atau sudah menikah','18 tahun','21 tahun'], correct:1},
  {q: 'Lembaga yang berwenang mengawasi jalannya Pemilu adalah...', a: ['KPU','Bawaslu','DPR','MPR'], correct:1},
  {q: 'Peserta Pemilu anggota DPR dan DPRD adalah...', a: ['Calon perseorangan','KPU','Organisasi masyarakat','Partai politik'], correct:3},
  {q: 'Peserta Pemilu anggota DPD berasal dari...', a: ['Partai politik','Calon perseorangan','DPR','Pemerintah daerah'], correct:1},
  {q: 'Apa yang dimaksud dengan suara sah dalam Pemilu?', a: ['Surat suara yang tidak dicoblos','Surat suara yang rusak','Surat suara yang dicoblos tepat pada satu kolom calon','Surat suara yang dicoblos diseluruh kolom calon'], correct:2},
  {q: 'Surat suara yang dicoblos lebih dari satu calon disebut...', a: ['Suara ganda','Suara batal','Suara rusak','Suara tidak sah'], correct:3},
  {q: 'Pemungutan suara dilakukan di...', a: ['Balai desa','TPS (Tempat Pemungutan Suara)','Gedung DPR','Rumah warga'], correct:1},
];